name: Build an push to AWS

on:
    push:
        branches:
            - "main"


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: Setup dotnet
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '6.0'
            
            - name: Restore dependencies
              run: dotnet restore
